; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:seeed_xiao]
platform = atmelsam
board = seeed_xiao
framework = arduino
lib_deps =
	dennis-ard/Arducam_Mega@^2.0.9
	greiman/SdFat@2.3.1
	jgromes/RadioLib@^7.1.2

[env:seeed_xiao_ra4m1]
platform = https://github.com/Seeed-Studio/platform-seeedboards.git
board = seeed-xiao-ra4m1
framework = arduino
lib_deps =
	dennis-ard/Arducam_Mega@^2.0.9
	greiman/SdFat@2.3.1
	jgromes/RadioLib@^7.1.2

[env:Unit_Tests_Win]
platform = native
build_flags = 
	-D UNITY_INT_WIDTH=32
	-D UNITY_FLOAT_TYPE=float_t
	-DRUNNING_WIN_NATIVE
test_build_src = yes
build_src_filter = 
	+<**/stats.cpp>
	+<test/*>
	-<.git/>
	-<.svn/>
